### ISSUE TITLE
[BUG] Particle Executable

### ISSUE THREAD

**Issue by ajowsey** [nrobinson2000/neopo#26]
**Describe the bug**
Cannot run neopo install due to particle binary error below. Consistent every time. In docker and my wsl instance. Starting around May 2nd. 

"
Installing neopo...
Finding Workbench extension URL...
Downloading Workbench extension...
Failed to download particle executable from extension!
"

**To Reproduce**
1. Start docker image for: "nrobinson2000/neopo" within bitbucket pipeline
2. Run neopo Install

**Expected behavior**
We have a pipeline that consistently uses nrobinson2000/neopo and it never fails usually. It should run the install and allows us to do subsequent calls. But we cannot run neopo configure or anything after 

**Screenshots**
![image](https://github.com/nrobinson2000/neopo/assets/12678565/c794cd8c-9322-4769-b7e1-655373f38cdc)
![image](https://github.com/nrobinson2000/neopo/assets/12678565/4d83f757-fc3b-4472-9619-07b440b5a576)

**Desktop (please complete the following information):**
 - OS: WSL ubuntu and nrobinson2000/neopo

**Additional context**
Release 6.1.0 was released around the same time. https://github.com/particle-iot/device-os/tags.

Seems related to https://community.particle.io/t/neopo-a-lightweight-solution-for-local-particle-development/56378/24?page=2

**Comment by ajowsey** [comment]
![image](https://github.com/nrobinson2000/neopo/assets/12678565/352d6fc1-a548-4cc7-a7ae-e0f62c9e7b0f)

Maybe the particle binaries path changed?

**Comment by ajowsey** [comment]
Appears the extensions files are missing
![image](https://github.com/nrobinson2000/neopo/assets/12678565/801d1ba4-c03f-45f6-817a-0e4ac1f65f34)

My older computer seems to have the populated files... Maybe particle changed something about their extension? I dont know where to find the source files for it...

**Comment by ajowsey** [comment]
andrew@Q-LTOP-42:~$ neopo versions
Available deviceOS versions:

   0.5.5         [ photon, p1, electron ]
   0.6.3         [ photon, p1 ]
   0.6.4         [ electron ]
   0.7.0         [ photon, p1, electron ]
   0.8.0-rc.10   [ photon, p1, electron ]
   0.8.0-rc.11   [ photon, p1, electron ]
   0.8.0-rc.12   [ photon, p1, electron ]
   0.8.0-rc.14   [ photon, p1, electron ]
   0.8.0-rc.25   [ argon, boron, xenon ]
   0.8.0-rc.26   [ argon, boron, xenon ]
   0.8.0-rc.27   [ argon, boron, xenon ]
   0.9.0         [ argon, boron, xenon ]
   1.0.0         [ photon, p1, electron ]
   1.0.1-rc.1    [ photon, p1, electron ]
   1.0.1         [ photon, p1, electron ]
   1.1.0-rc.1    [ photon, p1, electron, argon, boron, xenon ]
   1.1.0-rc.2    [ photon, p1, electron, argon, boron, xenon ]
   1.1.0         [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.1.1-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.1.1         [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.2.0-beta.1  [ photon, p1, electron, argon, boron, xenon ]
   1.2.0-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.2.1-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.2.1-rc.2    [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.2.1-rc.3    [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.2.1         [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.3.0-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.3.1-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.3.1         [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.4.0-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.4.0         [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.4.1-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.4.1         [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.4.2         [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.4.3         [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.4.4         [ photon, p1, electron, argon, boron, xenon, bsom ]
   1.5.0-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom, b5som ]
   1.5.0-rc.2    [ photon, p1, electron, argon, boron, xenon, bsom, b5som ]
   1.5.0         [ photon, p1, electron, argon, boron, xenon, bsom, b5som ]
   1.5.1-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom, b5som ]
   1.5.1         [ photon, p1, electron, argon, boron, xenon, bsom, b5som ]
   1.5.2         [ photon, p1, electron, argon, boron, xenon, bsom, b5som ]
   1.5.4-rc.1    [ photon, p1, electron, argon, boron, xenon, bsom, b5som, tracker ]
   1.5.4-rc.2    [ photon, p1, electron, argon, boron, xenon, bsom, b5som, tracker ]
   2.0.0-rc.1    [ photon, p1, electron, argon, boron, bsom, b5som ]
   2.0.0-rc.2    [ photon, p1, electron, argon, boron, bsom, b5som ]
   2.0.0-rc.3    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.0.0-rc.4    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.0.0         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.0.1         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.0.2-rc.1    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.0.2         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.1.0-rc.1    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.1.0         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.2.0-rc.1    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.2.0-rc.2    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.2.0         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.3.0-rc.1    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.3.0         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   2.3.1         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.0.0-beta.1  [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.0.0-rc.1    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.0.0-rc.2    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.0.0         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.1.0-rc.1    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.1.0         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.2.0-rc.1    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.2.0         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.3.0-rc.1    [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.3.0         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   3.3.1         [ photon, p1, electron, argon, boron, bsom, b5som, tracker ]
   4.0.0-alpha.1         [ argon, boron, bsom, b5som, tracker ]
   4.0.0-alpha.2         [ argon, boron, esomx, bsom, b5som, tracker ]
   4.0.0-beta.1  [ argon, boron, esomx, bsom, b5som, tracker ]
   4.0.0         [ argon, boron, esomx, bsom, b5som, tracker ]
   4.0.1-rc.1    [ argon, boron, esomx, bsom, b5som, tracker ]
   4.0.1         [ argon, boron, esomx, bsom, b5som, tracker ]
   4.0.2         [ argon, boron, esomx, bsom, b5som, tracker ]
   4.1.0         [ argon, boron, esomx, bsom, b5som, tracker ]
   4.2.0         [ argon, boron, esomx, bsom, b5som, tracker ]
   5.0.0-alpha.1         [ argon, boron, esomx, bsom, b5som, tracker, p2 ]
   5.0.0-alpha.2         [ argon, boron, esomx, bsom, b5som, tracker, p2 ]
   5.0.0         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2 ]
   5.0.1         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2 ]
   5.1.0         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2 ]
   5.2.0         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2 ]
   5.3.0         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2 ]
   5.3.1         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2 ]
   5.3.2         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2 ]
   5.4.0         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2 ]
   5.4.1         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2 ]
   5.5.0         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2, msom ]
   5.5.0-rc.1    [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2, msom ]
   5.6.0         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2, msom ]
   5.7.0         [ argon, boron, esomx, bsom, b5som, tracker, trackerm, p2, msom ]

Custom deviceOS versions:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/neopo/command.py", line 267, in main
    commands[args[1]](args)
  File "/usr/local/lib/python3.10/dist-packages/neopo/toolchain.py", line 129, in versions_command
    devices = ", ".join([platform_convert(platform, "id", "name", version)
  File "/usr/local/lib/python3.10/dist-packages/neopo/toolchain.py", line 129, in <listcomp>
    devices = ", ".join([platform_convert(platform, "id", "name", version)
  File "/usr/local/lib/python3.10/dist-packages/neopo/toolchain.py", line 46, in platform_convert
    platforms = get_custom_toolchain(custom_version, "platforms", True)
  File "/usr/local/lib/python3.10/dist-packages/neopo/toolchain.py", line 21, in get_custom_toolchain
    toolchain = data[component]
KeyError: 'platforms'
An unexpected error occurred!
To report this error on GitHub, please open an issue:
https://github.com/nrobinson2000/neopo/issues

**Comment by nrobinson2000** [comment]
Hey @ajowsey 

I've merged this PR which should fix all the bugs you are facing:
https://github.com/nrobinson2000/neopo/pull/27

Please give it a try and let me know if you have any more issues.

Also, I'm planning on doing a major rewrite of neopo in the near future, and I'm open to suggestions for new features.

**Comment by ajowsey** [comment]
Hey @nrobinson2000 thanks for the quick response.

Still no luck. I dont see any difference. We dont need to update the docker image right? It should have the latest and greatest.

**Comment by ajowsey** [comment]
Rerunning `bash <(curl -sL neopo.xyz/install) ` in my sandbox wsl seemed to get your changes. And those worked...

Not sure why the docker image doesnt get it.

**Comment by nrobinson2000** [comment]
The [image on Dockerhub](https://hub.docker.com/r/nrobinson2000/neopo) no longer auto deploys, since I was using the free build service which Docker has discontinued.

I should definitely clean up the Dockerfile, and can look into deploying the image with GitHub actions.

In the meantime, you can build the image yourself and host it on your own private registry like Amazon ECR if you’d like.

**Comment by ajowsey** [comment]
Sounds good. Will do!

And thanks for the heads up on the rewrite. We will try to gather some feedback! In general, some more integration with vscode would be neat. For instance, I like to bypass workbench extension, I wrote a bash script which I can trigger via vscode hotkeys to build images by parsing the settings.json and configuring neopo accordingly. And that bash will then use device-os-flash-util to flash multiple devices. Would be cool if that came along with the new neopo.

**Comment by sly4** [comment]
> The [image on Dockerhub](https://hub.docker.com/r/nrobinson2000/neopo) no longer auto deploys, since I was using the free build service which Docker has discontinued.
> 
> I should definitely clean up the Dockerfile, and can look into deploying the image with GitHub actions.
> 
> In the meantime, you can build the image yourself and host it on your own private registry like Amazon ECR if you’d like.

I had to change line 16 to add "--break-system-packages" flag to the pip install command.  My container would build, but fail to properly install neopo until I added this.

`python3 -m pip install --break-system-packages .`
